In [185]:
import pandas as pd
df_zigzag = pd.read_csv('data/Zigzag_baru.csv')

In [186]:
#Normalisasi Zigzag
from sklearn import preprocessing
import numpy as np

df_zigzag = df_zigzag.iloc[:,6:12]

x_array = np.array(df_zigzag ['AccelLPF x'])
AccelLPF_x_zigzag_norm = preprocessing.normalize([x_array])
x_array = np.array(df_zigzag ['AccelLPF y'])
AccelLPF_y_zigzag_norm = preprocessing.normalize([x_array])
x_array = np.array(df_zigzag ['AccelLPF z'])
AccelLPF_z_zigzag_norm = preprocessing.normalize([x_array])
x_array = np.array(df_zigzag ['GyroLPF x'])
GyroLPF_x_zigzag_norm = preprocessing.normalize([x_array])
x_array = np.array(df_zigzag ['GyroLPF y'])
GyroLPF_y_zigzag_norm = preprocessing.normalize([x_array])
x_array = np.array(df_zigzag ['GyroLPF z'])
GyroLPF_z_zigzag_norm = preprocessing.normalize([x_array])

In [187]:
import pandas as pd
df_mengantuk = pd.read_csv('data/Mengantuk_baru.csv')

In [188]:
#Normalisasi Mengantuk
from sklearn import preprocessing
import numpy as np

df_mengantuk = df_mengantuk.iloc[:,6:12]

x_array = np.array(df_mengantuk ['AccelLPF x'])
AccelLPF_x_mengantuk_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mengantuk ['AccelLPF y'])
AccelLPF_y_mengantuk_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mengantuk ['AccelLPF z'])
AccelLPF_z_mengantuk_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mengantuk ['GyroLPF x'])
GyroLPF_x_mengantuk_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mengantuk ['GyroLPF y'])
GyroLPF_y_mengantuk_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mengantuk ['GyroLPF z'])
GyroLPF_z_mengantuk_norm = preprocessing.normalize([x_array])

In [189]:
import pandas as pd 
df_mendadak=pd.read_csv('data/Rem_mendadak_baru.csv')

In [190]:
#Normalisasi Rem Mendadak
from sklearn import preprocessing
import numpy as np

df_mendadak = df_mendadak.iloc[:,6:12]

x_array = np.array(df_mendadak ['AccelLPF x'])
AccelLPF_x_mendadak_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mendadak ['AccelLPF y'])
AccelLPF_y_mendadak_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mendadak ['AccelLPF z'])
AccelLPF_z_mendadak_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mendadak ['GyroLPF x'])
GyroLPF_x_mendadak_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mendadak ['GyroLPF y'])
GyroLPF_y_mendadak_norm = preprocessing.normalize([x_array])
x_array = np.array(df_mendadak ['GyroLPF z'])
GyroLPF_z_mendadak_norm = preprocessing.normalize([x_array])

In [191]:
import pandas as pd 
df_tancapgas=pd.read_csv('data/Tancap_gas_baru.csv')

In [192]:
#Normalisasi Tancap Gas
from sklearn import preprocessing
import numpy as np

df_tancapgas = df_tancapgas.iloc[:,6:12]

x_array = np.array(df_tancapgas ['AccelLPF x'])
AccelLPF_x_tancapgas_norm = preprocessing.normalize([x_array])
x_array = np.array(df_tancapgas ['AccelLPF y'])
AccelLPF_y_tancapgas_norm = preprocessing.normalize([x_array])
x_array = np.array(df_tancapgas ['AccelLPF z'])
AccelLPF_z_tancapgas_norm = preprocessing.normalize([x_array])
x_array = np.array(df_tancapgas ['GyroLPF x'])
GyroLPF_x_tancapgas_norm = preprocessing.normalize([x_array])
x_array = np.array(df_tancapgas ['GyroLPF y'])
GyroLPF_y_tancapgas_norm = preprocessing.normalize([x_array])
x_array = np.array(df_tancapgas ['GyroLPF z'])
GyroLPF_z_tancapgas_norm = preprocessing.normalize([x_array])

In [193]:
dta_zigzag = [AccelLPF_x_zigzag_norm, AccelLPF_y_zigzag_norm, AccelLPF_z_zigzag_norm, GyroLPF_x_zigzag_norm, GyroLPF_y_zigzag_norm, GyroLPF_z_zigzag_norm]
dta_mengantuk = [AccelLPF_x_mengantuk_norm, AccelLPF_y_mengantuk_norm, AccelLPF_z_mengantuk_norm, GyroLPF_x_mengantuk_norm, GyroLPF_y_mengantuk_norm, GyroLPF_z_mengantuk_norm]
dta_mendadak = [AccelLPF_x_mendadak_norm, AccelLPF_y_mendadak_norm, AccelLPF_z_mendadak_norm, GyroLPF_x_mendadak_norm, GyroLPF_y_mendadak_norm,GyroLPF_z_mendadak_norm]
dta_tancapgas = [AccelLPF_x_tancapgas_norm, AccelLPF_y_tancapgas_norm, AccelLPF_z_tancapgas_norm, GyroLPF_x_tancapgas_norm, GyroLPF_y_tancapgas_norm, GyroLPF_z_tancapgas_norm]

In [194]:
#zigzag
zzg = []
buff = []
cage = 0
holding = 0
for a, b, c, d, e, f in zip(AccelLPF_x_zigzag_norm[0], AccelLPF_y_zigzag_norm[0], AccelLPF_z_zigzag_norm[0], GyroLPF_x_zigzag_norm[0], GyroLPF_y_zigzag_norm[0], GyroLPF_z_zigzag_norm[0]):
  cage = cage + 1
  buff.append(a)
  buff.append(b)
  buff.append(c)
  buff.append(d)
  buff.append(e)
  buff.append(f)
  if cage >= holding + 34:
    holding = cage
    zzg.append(buff)
    buff=[]

In [195]:
print(len(zzg))

151


In [196]:
#mengantuk
ngantuk = []
buff = []
cage = 0
holding = 0
for a, b, c, d, e, f in zip(AccelLPF_x_mengantuk_norm[0], AccelLPF_y_mengantuk_norm[0], AccelLPF_z_mengantuk_norm[0], GyroLPF_x_mengantuk_norm[0], GyroLPF_y_mengantuk_norm[0], GyroLPF_z_mengantuk_norm[0]):
  cage = cage + 1
  buff.append(a)
  buff.append(b)
  buff.append(c)
  buff.append(d)
  buff.append(e)
  buff.append(f)
  if cage >= holding + 34:
    holding = cage
    ngantuk.append(buff)
    buff=[]

In [197]:
print(len(ngantuk))

88


In [198]:
#rem mendadak
rem = []
buff = []
cage = 0
holding = 0
for a, b, c, d, e, f in zip(AccelLPF_x_mendadak_norm[0], AccelLPF_y_mendadak_norm[0], AccelLPF_z_mendadak_norm[0], GyroLPF_x_mendadak_norm[0], GyroLPF_y_mendadak_norm[0],GyroLPF_z_mendadak_norm[0]):
  cage = cage + 1
  buff.append(a)
  buff.append(b)
  buff.append(c)
  buff.append(d)
  buff.append(e)
  buff.append(f)
  if cage >= holding + 34:
    holding = cage
    rem.append(buff)
    buff=[]

In [199]:
print(len(rem))

66


In [200]:
#tancap gas
gas = []
buff = []
cage = 0
holding = 0
for a, b, c, d, e, f in zip(AccelLPF_x_tancapgas_norm[0], AccelLPF_y_tancapgas_norm[0], AccelLPF_z_tancapgas_norm[0], GyroLPF_x_tancapgas_norm[0], GyroLPF_y_tancapgas_norm[0], GyroLPF_z_tancapgas_norm[0]):
  cage = cage + 1
  buff.append(a)
  buff.append(b)
  buff.append(c)
  buff.append(d)
  buff.append(e)
  buff.append(f)
  if cage >= holding + 34:
    holding = cage
    gas.append(buff)
    buff=[]

In [201]:
print(len(gas))

99


In [202]:
dataset = []
for i in zzg: #setiap anggota zigzag menjadi i
  dataset.append([i,0]) #anggota i ditambahkan ke dataset
for i in ngantuk:
  dataset.append([i,1])
for i in rem:
  dataset.append([i,2])
for i in gas:
  dataset.append([i,3])

In [203]:
import random
random.shuffle(dataset) #mengacak semua dataset

In [204]:
print(dataset[0])

[[-0.011333669475964148, 0.01730471467630291, 0.019496295184959513, 0.005561603140969421, 0.03762667227922386, -0.0018011598565014634, -0.006063784555358124, 0.017078580055488932, 0.01959337629995813, 0.0037043574403732766, 0.02793093057885272, -0.010994400075396513, -0.0006297626736051759, 0.01747358577288581, 0.020119078231967118, -0.002944905766128442, 0.020149411021260336, -0.011994245612029227, 0.0015937434049434404, 0.017550347375123985, 0.018355069337554694, 0.014691874118224065, 0.006680929296738125, -0.014738215940070843, 0.004191003574054872, 0.004527985206434337, 0.0028012578675452623, -0.0007844789193260456, 0.0047768003275732605, 0.007645811107592589, 0.008016575791735288, 0.007863234108642954, 0.0060369178032333255, 0.00263344701715757, 0.02558693972021557, 0.01685983052903004, 0.008838796017862836, 0.009486701310596667, 0.008420530305985212, 0.0037368006071770263, 0.0367948823464856, 0.008090075909261096, 0.004971646935032815, 0.01079817297116167, 0.010478647393974604, 0

In [205]:
xx = [] #data training
yy = [] #label dari dataset
for i in dataset:
  xx.append(np.array(i[0]))
  yy.append(i[1])

In [206]:
print(xx[0].shape)

(204,)


In [207]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import numpy as np

from matplotlib import pyplot as plt
%matplotlib inline

In [208]:
X_train, X_test, y_train, y_test = train_test_split(np.array(xx), np.array(yy), test_size=0.2)

In [209]:
print(y_test)

[3 0 0 0 2 1 1 0 1 3 1 2 0 0 0 3 1 0 1 1 3 1 3 0 0 0 0 1 0 1 0 0 2 3 1 3 2
 2 2 3 3 0 1 0 3 2 1 0 2 0 2 3 0 1 0 0 0 0 3 1 3 2 0 1 0 0 3 3 1 2 0 1 3 0
 3 0 1 3 0 0 0]


In [210]:
print(np.array(X_train).shape) 
# d2_train_dataset = X_train.reshape((nsamples,nx*ny))

(323, 204)


In [211]:
model = SVC(kernel='linear', C=1E4, max_iter=-1)

In [212]:
model.fit(X_train, y_train)

SVC(C=10000.0, kernel='linear')

In [213]:
predictions = model.predict(X_test)
print(predictions)

[3 0 0 0 2 2 1 0 3 2 1 3 0 0 0 3 2 0 2 1 1 1 3 0 0 0 0 1 0 2 0 0 3 1 1 1 1
 2 1 3 1 0 1 0 3 2 1 0 1 0 1 0 0 1 0 0 0 0 0 3 3 2 3 1 0 0 3 1 1 2 0 1 3 0
 3 0 1 3 0 0 0]


In [214]:
percentage = model.score(X_test, y_test)

In [215]:
from sklearn.metrics import confusion_matrix
res = confusion_matrix(y_test, predictions)
print("Confusion Matrix")
print(res)
print(f"Test Set: {len(X_test)}")
print(f"Accuracy = {percentage*100} %")

Confusion Matrix
[[32  0  0  1]
 [ 0 13  4  2]
 [ 0  4  5  2]
 [ 2  5  1 10]]
Test Set: 81
Accuracy = 74.07407407407408 %
